"use strict";

var drawbacks = [
    {Title:"A Tiger By The Tail", Body:"<p><strong>A Tiger By The Tail</strong><br/>You own a very dangerous wild animal, bigger than a human and either an apex predator or a very dangerous herbivore. You love it dearly and unconditionally, and can't realize just how obscenely dangerous it is until after the Jump ends. No matter how powerful someone is, it can still hurt them, and is only harmless to you and anyone who you'd <em>want</em> it to hurt. This is a drawback; I'm not letting your pet demontiger be in any way <em>useful.</em></p>"},
    {Title:"Niko, Cousin!", Body:"<p><strong>Niko, Cousin!</strong><br/>Someone who you have to keep happy keeps calling you at inconvenient times to ask if you want to go bowling. It does not necessarily have to be bowling, but if your main concern is that it wouldn't make sense for bowling alleys to exist, then ignore that concern and keep it anyways. It's funnier this way.</p>"},
    {Title:"Collecting Bottlecaps", Body:"<p><strong>Collecting Bottlecaps</strong><br/>You develop an overpowering obsession with collecting some random, useless trinket. Funko Pops are a good example that nobody is allowed to use- come up with literally anything else that happens to be in that same ballpark of useless garbage. Your highest priority, for the duration of that Jump, will be to collect one of everything in that category, and everything useful or plot relevant you do will be because you saw it as a way to protect or expand your collection of useless crap. This useless crap doesn't have to stay useless, but it can't be obviously useful, like trading cards in a Yugioh Jump. Waifus do not, under any circumstances, count as collectible, no matter how useless or \"garbage\" you think they are.</p>"},
    {Title:"Prequels Fanboy", Body:"<p><strong>Prequels Fanboy</strong><br/>You have a deep, abiding affection for a widely unpopular piece of media. Not unpopular as in nobody's heard of it, unpopular as in nobody likes it. Whenever someone trash-talks it, which will happen often enough for this flaw to come into play, you get upset and feel compelled to defend, at length, your favorite piece of garbage. Appropriate candidates include, but are not limited to, Highlander 2, Bubsy The Bobcat, and 009 Sound System.</p>"},
    {Title:"Stuffed Schedule", Body:"<p><strong>Stuffed Schedule</strong><br/>Every time you try to schedule something with someone else, or vice versa, you realize how busy you retroactively are at that time frame, and are obliged to spend at least two minutes quibbling over dates, locations, and exact times. This doesn't meaningfully stop you from doing anything, it just makes you stand around with a day planner and a pencil every now and then.</p>"},
    {Title:"Let Me Tell You About Homestuck", Body:"<p><strong>Let Me Tell You About Homestuck</strong><br/>You have a deep, abiding affection for an obscure and complicated piece of media. Whenever someone asks about your interests, you feel compelled to explain the details and nuances of this obscure piece of media at excruciating length, with absolutely no guarantee whatsoever that they'll give a shit. Appropriate candidates include, but are not limited to, Animorphs, Jumpchain itself, and whatever utterly deranged fetishy anime you scraped off the bottom of the barrel.</p>"},
    {Title:"I'd Kill For A Hamburger", Body:"<p><strong>I'd Kill For A Hamburger</strong><br/>Pick one arbitrary food or meal you like. It doesn't exist at all in the setting of this Jump, and you miss it terribly, lamenting its absence and raving about its virtues whenever someone asks what you're sad about this time. Attempts at recreating this food are bound to be disappointing; you'll overcook it or you'll be missing a vital ingredient and be forced to make an imperfect substitution or something else. It'll be okay-ish, but not what you're really craving, and nobody else who tries it will understand what you're missing.</p>"},
    {Title:"The Jokester", Body:"<p><strong>The Jokester</strong><br/>For the duration of your Jump, you will be haunted by an invincible superclown who is absolutely determined to make a jackass out of you, whenever you least expect it. It'll never be harmful or even materially inconvenient; the only damage will be to your pride. Still, expect whoopee cushions on your chair and pies to the face every so often.</p>"},
    {Title:"You Live Like This?", Body:"<p><strong>You Live Like This?</strong><br/>For the duration of your Jump, you have a living space of your own that nobody else can be made responsible for cleaning up or maintaining, and you become wholly uninterested or unwilling to clean it up or maintain it in any meaningful way. If you ever let someone into this space, they will remark on how atrociously filthy your lifestyle is.</p>"},
    {Title:"I Prefer Jonathan", Body:"<p><strong>I Prefer Jonathan</strong><br/>You prefer to go by your full first name, and unfortunately, everyone else prefers to call you a reasonable shortening of your full first name. Williams are going to get called Bill a lot, and Samanthas are going to hear a lot of Sams. This bugs you a lot, more than it normally would, and you feel the urge to correct people every time it happens. If your full first name is already one syllable, either pick a name that your name could plausibly be a shortening of, or pick a new name entirely.</p>"},
    {Title:"It's Pronounced Katelyn", Body:"<p><strong>It's Pronounced Katelyn</strong><br/>Your name is spelled very, very strangely, and nobody knows how to pronounce it until they hear it said out loud. That won't stop them from trying and failing, though; expect your name to get butchered like a hobby farmer's first chicken on the regular. The idea of changing how your name is spelled is offensive to you, and you refuse to entertain the idea.</p>"},
    {Title:"Not That Kind Of Doctor", Body:"<p><strong>Not That Kind Of Doctor</strong><br/>You have a (potentially honorary) Doctorate in some field of study that is neither medicine nor particularly useful for whatever you're trying to accomplish this Jump. This does not earn you any particular respect, useful skills, or job security, and instead seems to just constantly land you in pissing matches about whether or not you really deserve to be called \"Doctor,\" which you are very insistent you do.</p>"},
    {Title:"Lock The Door", Body:"<p><strong>Lock The Door</strong><br/>You have a nasty habit of walking in on people doing embarrassing things you don't want to see. You can chime in with a \"haven't you people ever heard of closing the goddamn door\" all you want, but it'll keep happening. It's never going to be anything traumatic or life-changing. You just get to learn that your friend owns a blow-up doll, or that your boss has Irritable Bowel Syndrome.</p>"},
    {Title:"Don't You People Know How To Knock?", Body:"<p><strong>Don't You People Know How To Knock?</strong><br/>You have a nasty tendency of being interrupted while you're doing anything harmless yet embarrassing, such as having sex with your openly-acknowledged lover, trying on a really dumb/weird-looking costume, painting Warhammer miniatures, or building a house of cards. Nobody's going to think much less of you for having interests, but they might have trouble looking you in the eye for a few days.</p>"},
    {Title:"Don't Quit Your Day Job", Body:"<p><strong>Don't Quit Your Day Job</strong><br/>Nobody thinks you're funny. You frequently make the dumbest, worst jokes anyone has ever heard, and absolutely nobody will think you're funny. Some of them might pretend otherwise, with varying degrees of convincingness, and others might find your ineptitude endearing, but for the most part, people cringe every time you open your mouth.</p>"},
    {Title:"Snake Oil", Body:"<p><strong>Snake Oil</strong><br/>You have a product. It's not very good. You either don't know or don't care, and take every opportunity available- and a few that aren't- to hawk it, whether or not the audience is receptive, which they usually aren't.</p>"},
    {Title:"Horses Aren't Real", Body:"<p><strong>Horses Aren't Real</strong><br/>You believe, with total, unflappable confidence, something utterly bizarre, patently untrue, and largely inconsequential, on the order of \"kittens hatch from eggs\" or \"birds are actually government surveillance drones.\" Furthermore, you will expound on this belief at length when prompted, questioned, or challenged, whether it's a good idea or not. You're not allowed to use real-world conspiracy theories, it has to be some bespoke meaningless nonsense that some chud hasn't yet turned into an antisemitic dogwhistle. Get creative.</p>"},
    {Title:"Austin Powers' Teeth", Body:"<p><strong>Austin Powers' Teeth</strong><br/>No matter how perfect you are, there's at least one quality you have that everyone dislikes. They can like the rest of you just fine, and politely ignore the quality they don't, but they'll still make the occasional face or snide comment about it, which will get on your nerves after a while. You cannot and will not even attempt to correct or change this quality for as long as the Jump lasts, and any external attempts to change or correct it will achieve nothing but wasting your time and pissing you off.</p>"},
    {Title:"Marquis du Laughy-At", Body:"<p><strong>Marquis du Laughy-At</strong><br/>You're such a laughable edgelord, people learn trivia like \"a marquis is the count of a border county, making them a literal edgelord\" just to make fun of you more effectively. You frequently make edgy proclamations that nobody else takes seriously, and everyone has something smarmy to say about your latest declaration of misanthropy.</p>"},
    {Title:"Enthusiastic Amateur", Body:"<p><strong>Enthusiastic Amateur</strong><br/>You have a passion for something- a hobby, a game, a field of study- that you are absolutely terrible at. It's largely inconsequential, but you're just absolute dogshit at it, managing to be even worse than any random guy off the street. It's up to you whether or not you're <em>aware</em> of how bad you suck; pick whichever one you think is funnier. It's recommended you not pick a creative hobby. We don't need more stories about authors who think they're better than they actually are. We've all met enough of them as it is.</p>"},
    {Title:"Eau De Toilet", Body:"<p><strong>Eau De Toilet</strong><br/>Bitch you stink. Regardless of your hygiene habits- which will be greatly deteriorated with no way of really fixing them long-term- you are going to constantly smell awful. People will still tolerate you and perhaps even like you, but expect several sticks of deodorant, bars of soap, cans of body spray, and tins of breathmints as gag gifts for the next ten years.</p>"},
    {Title:"Head In The Clouds", Body:"<p><strong>Head In The Clouds</strong><br/>When people talk, you don't always listen. You space out, and think about Batman, or the politics of Freeman Dyson, or how dumb it is for these peasants to have a windmill when they've got a perfectly serviceable waterfall right there just begging for a waterwheel, instead of the more immediately relevant stuff happening at you. You <em>probably</em> won't miss any important information, and can ask people to summarize whatever it is they just lectured you about, although if the plot works better if you <em>do</em> miss important information... Well, I'm not going to discourage that.</p>"},
    {Title:"I Studied The Blade", Body:"<p><strong>I Studied The Blade</strong><br/>You have a fairly specific favorite sort of weapon- which <em>can</em> be the katana but, come on, shake it up a bit- that you stubbornly believe is superior to all others, contrary to all available evidence, and even if it has no bearing on your daily life. Furthermore, you believe yourself to be a grandmaster with this weapon, but in fact are capable of nothing more than making cool poses while imagining yourself as a movie star. Despite all this, you <em>are</em> willing to use other, more contextually-appropriate weapons, you'll just complain about their inferiority to your weapon of choice.</p>"},
    {Title:"Gamblin' Man", Body:"<p><strong>Gamblin' Man</strong><br/>You have a gambling addiction. Maybe it's as innocent as nobody letting you anywhere near a casino, talking about that time you lost all your money to the one-armed bandit, or maybe it's as serious as kicking off a major plot point in which you owe huge amounts in gambling debts to organized crime syndicates who, come hell or high water, <em>will</em> try to get that money out of you. Or maybe you're just constantly playing Gacha games on your phone. Up to you, really.</p>"},
    {Title:"Do Not Call", Body:"<p><strong>Do Not Call</strong><br/>You are frequently, annoyingly beset by telemarketers and door-to-door salesmen. Mormons and Jehova's Witnesses, or the local equivalent- or both, if it's funnier that way- knock on your front door once a week, no matter what. Even if you're on a space ship. They will find a way.</p>"},
    {Title:"But Mom...", Body:"<p><strong>But Mom...</strong><br/>An overbearing authority figure who thinks they're your parent is permanently, inescapably involved in your life for the duration of the Jump's plot. They don't do anything useful for you or give you any good advice, and seem to exist solely to get in your way and treat you like a child. For the sake of those who grew up with shitty parents, the option exists to either reroll- even if you don't normally allow those- or to have this authority figure be the final boss of the Jump's plot, allowing you to have a JRPG-esque climax where you kill your evil dad who may or may not also be God.</p>"},
    {Title:"Inhospitable", Body:"<p><strong>Inhospitable</strong><br/>You have a permanent houseguest who, for whatever reason, you cannot bring yourself to be rid of, and who constantly gets on your nerves, eating your leftovers that were <em>clearly marked</em> as belonging to you, not cleaning up after themselves, and/or misusing your good art supplies without asking.</p>"},
    {Title:"Copycat", Body:"<p><strong>Copycat</strong><br/>No matter what you do for the world, no matter what world-shattering feats you bring about, hardly anybody thinks <em>you</em> did it. Some other asshole who happens to resemble you is getting all the credit for your hard work. Or, if you'd prefer, you can flip the script; <em>you</em> keep getting held responsible for everything that asshole who resembles you does. In either case, attempting to track them down so you can kick their ass will prove to be a herculean, plot-defining task, if you think it's worth it.</p>"},
    {Title:"Dan John", Body:"<p><strong>Dan John</strong><br/>You frequently act, unconvincingly, like you have a lot of sex with a lot of people. Nobody actually believes you, even if you really do, in fact, have a lot of sex with a lot of people. Maybe it's just a bit you're doing, and everyone's in on the joke. Or maybe you're just pathetic.</p>"},
    {Title:"Where's That Walkthrough?", Body:"<p><strong>Where's That Walkthrough?</strong><br/>Frequently, you will be stopped in your tracks by some manner of puzzle- a logic puzzle about arranging colored stones, the Towers of Hanoi, or maybe a sliding tile puzzle. You cannot progress without solving the puzzle, and any supernatural abilities- from the Jumpchain itself or otherwise- that would trivialize the puzzle simply don't. Maybe it's hard enough that even your powers struggle with it, maybe they simply don't work, or maybe the simple act of going through the motions to implement the solution take an inconveniently long time.</p>"},
    {Title:"Sticky Fingers", Body:"<p><strong>Sticky Fingers</strong><br/>No matter what you do to prevent it, you <em>will</em> get your pockets picked at some point. It probably isn't going to ruin your life, and if you <em>notice</em> the pickpocket you can stop them and take your wallet back, but it's still going to be annoying and stressful.</p>"},
    {Title:"Chirality", Body:"<p><strong>Chirality</strong><br/>You know how, in the real world, something like ninety percent of people are right-handed? Well, now it's the opposite- in this Jump, ninety percent of everyone <em>native</em> to the local universe is left-handed. Those who Import, yourself and Companions included, are still probably right-handed, though. Depending on social attitudes of the time, people might think you're the devil, unhygenic, or it might be that the worst problem is that everything is designed with southpaws in mind. You can still take this drawback if you're already left-handed, though, and rub it in the faces of all your right-handed Companions.</p>"},
    {Title:"Apples Come In Different Colors?", Body:"<p><strong>Apples Come In Different Colors?</strong><br/>You're now red-green colorblind. How this inconvenient this is in your life is mainly up to you- maybe you don't notice because your wardrobe leans more towards blues, or maybe you get a lot of people killed because you cut the wrong wire. One thing's for sure, though, when you tell people, they'll be excited to show you a marker and ask \"what color is this?\" Trust me, it gets annoying.</p>"},
    {Title:"Whale, Axially", Body:"<p><strong>Whale, Axially</strong><br/>You tend to speach in ways that are almost correct, and frequently, some pendantic nitwit takes it upon themselves to connect you. Or maybe you <em>don't</em> speak in an \"almost correct\" mannerism, and this obnoxious poindexter is merely confidently wrong- so confidently that you can't get <em>them</em> to accept correction. Either way, no matter how many lockers you shove them into, you'll never be folly rid of this archetype.</p>"},
    {Title:"I Poupon My Burgers", Body:"<p><strong>I Poupon My Burgers</strong><br/>For whatever reason, you keep noticing the filthiest double-entendres in supposedly-innocuous advertisements. Nobody else notices them, and thinks you're either insane or simply puerile when you try to explain the obvious-to-you innuendo.</p>"},
    {Title:"I Hate Coconut", Body:"<p><strong>I Hate Coconut</strong><br/>There's a common, popular food, ingredient, or flavor that you hate the taste or texture or aftertaste of. Whatever it is, you can't stand it. And for whatever goddamn reason, nobody can take no for an answer, and keeps trying to feed it to you, either through simple peer pressure, or lying to you about what they're feeding you. Attempting to lie and say you're allergic will only dissuade most of them. Attempting to <em>truthfully</em> tell people you're allergic will have the same results. Yes, people will try to feed you something you're genuinely allergic to. </p>"},
];



function generatePage(){
    var companionCount = $('#count').val();
    var companions = [];
    var parent = document.getElementById('output');
    $('#output').empty();

    companions.push({title: "Jumper", drawback: rollDrawback()});
    for (var i = 1; i <= companionCount; i++) {
        if(Math.ceil(Math.random() * 2) == 2){
            companions.push({title: ("Companion #"+(i)), drawback: rollDrawback()});
        } else {
            companions.push({title: ("Companion #"+(i)), drawback: {Title:"None", Body:"<p><strong>No Drawback</strong><br>This companion does not have a drawback... <em>this time.</em></p>"}});
        }
    }

    for (var i = 0; i <= companionCount; i++) {
        $('#output').append('<div class="col-xs-12 centered"><div class="card"><div class="card-header">'+companions[i].title+'</div><div class="card-body">'+companions[i].drawback.Body+'</div></div></div>\n');
    }
}

function rollDrawback(){
    var roll = Math.floor(Math.random() * 36)
    return drawbacks[roll];
}

$(document).ready(function () {
    $("#reroll").click(function () {
        generatePage();
    });
    generatePage();
});
